Update CI-Windows.yml

diff --git a/.github/workflows/CI-Windows.yml b/.github/workflows/CI-Windows.yml
--- a/.github/workflows/CI-Windows.yml
+++ b/.github/workflows/CI-Windows.yml
@@ -1,5 +1,5 @@
 ---
-name: CIWin
+name: CI-Windows
 
 on:
   pull_request:
@@ -122,8 +122,6 @@ jobs:
       release_body: ${{ env.RELEASE_BODY }}
       pre_release: ${{ steps.release_details.outputs.pre_release }}
 
-
-
   build_win:
     name: Windows
     runs-on: windows-2019
@@ -135,6 +133,110 @@ jobs:
         with:
           submodules: recursive
 
+      - name: Prepare tests
+        id: prepare-tests
+        if: false  # todo: DirectX11 is not available, so even software encoder fails
+        run: |
+          # function to download and extract a zip file
+          function DownloadAndExtract {
+            param (
+              [string]$Uri,
+              [string]$OutFile
+            )
+
+            $maxRetries = 5
+            $retryCount = 0
+            $success = $false
+
+            while (-not $success -and $retryCount -lt $maxRetries) {
+              $retryCount++
+              Write-Host "Downloading $Uri to $OutFile, attempt $retryCount of $maxRetries"
+              try {
+                Invoke-WebRequest -Uri $Uri -OutFile $OutFile
+                $success = $true
+              } catch {
+                Write-Host "Attempt $retryCount of $maxRetries failed with error: $($_.Exception.Message). Retrying..."
+                Start-Sleep -Seconds 5
+              }
+            }
+
+            if (-not $success) {
+              Write-Host "Failed to download the file after $maxRetries attempts."
+              exit 1
+            }
+
+            # use .NET to get the base name of the file
+            $baseName = (Get-Item $OutFile).BaseName
+
+            # Extract the zip file
+            Expand-Archive -Path $OutFile -DestinationPath $baseName
+          }
+
+          # virtual display driver
+          DownloadAndExtract `
+            -Uri "https://www.amyuni.com/downloads/usbmmidd_v2.zip" `
+            -OutFile "usbmmidd_v2.zip"
+
+          # install
+          Set-Location -Path usbmmidd_v2/usbmmidd_v2
+          ./deviceinstaller64 install usbmmidd.inf usbmmidd
+
+          # create the virtual display
+          ./deviceinstaller64 enableidd 1
+
+          # move up a directory
+          Set-Location -Path ../..
+
+          # install devcon
+          DownloadAndExtract `
+            -Uri "https://github.com/Drawbackz/DevCon-Installer/releases/download/1.4-rc/Devcon.Installer.zip" `
+            -OutFile "Devcon.Installer.zip"
+          Set-Location -Path Devcon.Installer
+          # hash needs to match OS version
+          # https://github.com/Drawbackz/DevCon-Installer/blob/master/devcon_sources.json
+          Start-Process -FilePath "./Devcon Installer.exe" -Wait -ArgumentList `
+            'install', `
+            '-hash', '54004C83EE34F6A55380528A8B29F4C400E61FBB947A19E0AB9E5A193D7D961E', `
+            '-addpath', `
+            '-update', `
+            '-dir', 'C:\Windows\System32'
+
+          # disable Hyper-V Video
+          # https://stackoverflow.com/a/59490940
+          C:\Windows\System32\devcon.exe disable "VMBUS\{da0a7802-e377-4aac-8e77-0558eb1073f8}"
+
+          # move up a directory
+          Set-Location -Path ..
+
+          # multi monitor tool
+          DownloadAndExtract `
+            -Uri "http://www.nirsoft.net/utils/multimonitortool-x64.zip" `
+            -OutFile "multimonitortool.zip"
+
+          # enable the virtual display
+          # http://www.nirsoft.net/utils/multi_monitor_tool.html
+          Set-Location -Path multimonitortool
+
+          # Original Hyper-V is \\.\DISPLAY1, it will recreate itself as \\.\DISPLAY6 (or something higher than 2)
+          # USB Mobile Monitor Virtual Display is \\.\DISPLAY2
+
+          # these don't seem to work if not using runAs
+          # todo: do they work if not using runAs?
+          Start-Process powershell -Verb runAs -ArgumentList '-Command ./MultiMonitorTool.exe /enable \\.\DISPLAY2'
+          Start-Process powershell -Verb runAs -ArgumentList '-Command ./MultiMonitorTool.exe /SetPrimary \\.\DISPLAY2'
+
+          # wait a few seconds
+          Start-Sleep -s 5
+
+          # list monitors
+          ./MultiMonitorTool.exe /stext monitor_list.txt
+
+          # wait a few seconds
+          Start-Sleep -s 5
+
+          # print the monitor list
+          Get-Content -Path monitor_list.txt
+
       - name: Setup Dependencies Windows
         uses: msys2/setup-msys2@v2
         with:
@@ -142,12 +244,14 @@ jobs:
           install: >-
             base-devel
             diffutils
+            doxygen
             git
             make
             mingw-w64-x86_64-binutils
             mingw-w64-x86_64-boost
             mingw-w64-x86_64-cmake
             mingw-w64-x86_64-curl
+            mingw-w64-x86_64-graphviz
             mingw-w64-x86_64-miniupnpc
             mingw-w64-x86_64-nlohmann-json
             mingw-w64-x86_64-nodejs
@@ -159,6 +263,24 @@ jobs:
             nasm
             wget
             yasm
+
+      - name: Setup python
+        # use this instead of msys2 python due to known issues using wheels, https://www.msys2.org/docs/python/
+        id: setup-python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+
+      - name: Python Path
+        id: python-path
+        shell: msys2 {0}
+        run: |
+          # replace backslashes with double backslashes
+          python_path=$(echo "${{ steps.setup-python.outputs.python-path }}" | sed 's/\\/\\\\/g')
+
+          # step output
+          echo "python-path=${python_path}"
+          echo "python-path=${python_path}" >> $GITHUB_OUTPUT
 
       - name: Build Windows
         shell: msys2 {0}
@@ -173,6 +295,8 @@ jobs:
             -DBUILD_WERROR=ON \
             -DCMAKE_BUILD_TYPE=RelWithDebInfo \
             -DSUNSHINE_ASSETS_DIR=assets \
+            -DTESTS_PYTHON_EXECUTABLE='${{ steps.python-path.outputs.python-path }}' \
+            -DTESTS_SOFTWARE_ENCODER_UNAVAILABLE='skip' \
             -G "MinGW Makefiles" \
             ..
           mingw32-make -j$(nproc)
@@ -191,14 +315,47 @@ jobs:
           mv ./cpack_artifacts/Sunshine.exe ../artifacts/sunshine-windows-installer.exe
           mv ./cpack_artifacts/Sunshine.zip ../artifacts/sunshine-windows-portable.zip
 
+      - name: Run tests
+        id: test
+        shell: msys2 {0}
+        working-directory: build/tests
+        run: |
+          ./test_sunshine.exe --gtest_color=yes
+
+      - name: Generate gcov report
+        # any except canceled or skipped
+        if: always() && (steps.test.outcome == 'success' || steps.test.outcome == 'failure')
+        id: test_report
+        shell: msys2 {0}
+        working-directory: build
+        run: |
+          ${{ steps.python-path.outputs.python-path }} -m pip install gcovr
+          ${{ steps.python-path.outputs.python-path }} -m gcovr -r .. \
+            --exclude ../tests/ \
+            --exclude ../third-party/ \
+            --xml-pretty \
+            -o coverage.xml
+
+      - name: Upload coverage
+        # any except canceled or skipped
+        if: always() && (steps.test_report.outcome == 'success')
+        uses: codecov/codecov-action@v3
+        with:
+          files: ./build/coverage.xml
+          flags: ${{ runner.os }}
+
       - name: Package Windows Debug Info
         working-directory: build
         run: |
-          # save the original binaries with debug info
+          # use .dbg file extension for binaries to avoid confusion with real packages
+          Get-ChildItem -File -Recurse | `
+            % { Rename-Item -Path $_.PSPath -NewName $_.Name.Replace(".exe",".dbg") }
+
+          # save the binaries with debug info
           7z -r `
             "-xr!CMakeFiles" `
             "-xr!cpack_artifacts" `
-            a "../artifacts/sunshine-debuginfo-win32.zip" "*.exe"
+            a "../artifacts/sunshine-win32-debuginfo.7z" "*.dbg"
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
